version: "2.0"
services:
  qbittorrent:
    image: nevinee/qbittorrent
    container_name: qbittorrent
    restart: always
    tty: true
    network_mode: bridge
    hostname: qbitorrent
    volumes:
      - ./data:/data
    environment:
      - WEBUI_PORT=8080   # WEBUI控制端口，可自定义
      - BT_PORT=34567     # BT监听端口，可自定义
      - TZ=Asia/Shanghai  # 时区
    ports:
      - 8080:8080        # 冒号左右一致，必须同WEBUI_PORT
      - 34567:34567      # 冒号左右一致，必须同BT_PORT
      - 34567:34567/udp  # 冒号左右一致，必须同BT_PORT
