bind_host: 0.0.0.0
bind_port: 3000
beta_bind_port: 0
users:
- name: root
  password: $2y$10$rQgelARtYXo8DwhQEkEHi.DDDwHXfaZk3Y/KuxOBcsBcTnxqO8SzK
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: zh-cn
rlimit_nofile: 0
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
  - 0.0.0.0
  port: 5553
  statistics_interval: 30
  querylog_enabled: true
  querylog_file_enabled: true
  querylog_interval: 30
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
  - tls://dns.pub
  - https://dns.pub/dns-query
  - tls://dns.alidns.com
  - https://dns.alidns.com/dns-query
  upstream_dns_file: ""
  bootstrap_dns:
  - 119.29.29.29
  - 223.5.5.5
  - 180.76.76.76
  - 114.114.114.114
  - 114.114.115.115
  all_servers: true
  fastest_addr: false
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
  - version.bind
  - id.server
  - hostname.bind
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  bogus_nxdomain: []
  aaaa_disabled: true
  enable_dnssec: true
  edns_client_subnet: true
  max_goroutines: 300
  ipset: []
  filtering_enabled: true
  filters_update_interval: 24
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites: []
  blocked_services: []
  local_domain_name: lan
  resolve_clients: true
  local_ptr_upstreams: []
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
- enabled: true
  url: https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt
  name: easylistchina+easylist
  id: 1613813149
- enabled: true
  url: https://easylist-downloads.adblockplus.org/easyprivacy.txt
  name: easyprivacy
  id: 1613813150
- enabled: true
  url: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-ublock.txt
  name: cjx-ublock
  id: 1613813151
- enabled: true
  url: https://anti-ad.net/easylist.txt
  name: anti-ad
  id: 1613813152
- enabled: true
  url: https://adaway.org/hosts.txt
  name: AdAway
  id: 1613813153
- enabled: true
  url: https://gitee.com/xinggsf/Adblock-Rule/raw/master/rule.txt
  name: rule  乘风 广告
  id: 1613813154
- enabled: true
  url: https://gitee.com/xinggsf/Adblock-Rule/raw/master/mv.txt
  name: 乘风 视频
  id: 1613813155
- enabled: true
  url: https://www.i-dont-care-about-cookies.eu/abp/
  name: I don't care about cookies
  id: 1613813157
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard DNS filter
  id: 1614422613
- enabled: true
  url: https://cdn.jsdelivr.net/gh/neoFelhz/neohosts@gh-pages/basic/hosts.txt
  name: neoHosts basic
  id: 1614422616
- enabled: true
  url: https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts
  name: 1024host
  id: 1614422618
- enabled: true
  url: https://raw.githubusercontent.com/neodevpro/neodevhost/master/adblocker
  name: NEO DEV HOST
  id: 1614422621
- enabled: true
  url: https://banbendalao.coding.net/p/adgk/d/ADgk/git/raw/master/ADgk.txt
  name: adgk AdGuard for Android 手机去广告规则
  id: 1618457840
- enabled: true
  url: https://cdn.jsdelivr.net/gh/o0HalfLife0o/list@master/ad.txt
  name: halflife
  id: 1618457841
- enabled: true
  url: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
  name: Adblock Warning Removal List 去除禁止广告拦截提示规则
  id: 1618457842
whitelist_filters: []
user_rules:
- '@@||rarbgunblocked.org^$important'
- /assistant.tv.mi.com/
- /redirect.pandora.xiaomi.com/
- /file.xmpush.xiaomi.com/
- /assistant.pandora.xiaomi.com/
- /api.io.mi.com/
- /lbs.pandora.xiaomi.com/
- /cn.app.chat.xiaomi.net/
- /ot.io.mi.com/
- /broker.mqtt.pandora.xiaomi.com/
- /assistant.sys.tv.mi.com/
- /api.ai.xiaomi.com/
- /port.sec.miui.com/
- /ad.xiaomi.com/
- /ad1.xiaomi.com/
- /ad.mi.com/
- /tat.pandora.xiaomi.com/
- /stat.pandora.xiaomi.com/
- /mishop.pandora.xiaomi.com/
- /upgrade.mishop.pandora.xiaomi.com/
- /dvb.pandora.xiaomi.com/
- /de.pandora.xiaomi.com/
- /jellyfish.pandora.xiaomi.com/
- /gallery.pandora.xiaomi.com/
- /bss.pandora.xiaomi.com/
- /data.mistat.xiaomi.com/
- /o2o.api.xiaomi.com/
- /gvod.aiseejapp.atianqi.com/
- /milink.pandora.xiaomi.com/
- /weatherapi.market.xiaomi.com/
- /shop.pandora.xiaomi.com/
- /pandora.mi.com/
- /open.account.xiaomi.com/
- /ott.io.mi.com/
- /app.chat.xiaomi.net/
- '||t7z.cupid.ptqy.gitv.tv^$important'
- '@@||g.live.com^$important'
- '@@||s.click.taobao.com^$important'
- '@@||dg.k.jd.com^$important'
- '@@||jd.com^$important'
- '@@||isub.snssdk.com^$important'
- '@@||snssdk.com^$important'
- '@@||toutiao.com^$important'
- '@@||ctobsnssdk.com^$important'
- '@@||pangolin-sdk-toutiao.com^$important'
- '@@||umeng.com^$important'
- '@@||umengcloud.com^$important'
dhcp:
  enabled: false
  interface_name: ""
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients: []
log_compress: false
log_localtime: false
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_file: ""
verbose: false
schema_version: 10
